------------------------SEMI PROJECT DDL -------------------------﻿
------- SEQUENCE -------
DROP SEQUENCE "SEQ_NOTICEBOARD_ID";
CREATE SEQUENCE "SEQ_NOTICEBOARD_ID";
DROP SEQUENCE "SEQ_BOARD_ID";
CREATE SEQUENCE "SEQ_BOARD_ID";
DROP SEQUENCE "SEQ_REVIEW_ID";
CREATE SEQUENCE "SEQ_REVIEW_ID";

------- TABLE -------
------- DROP -------
DROP TABLE "REPLY2_REPORT";
DROP TABLE "REPLY1_REPORT";
DROP TABLE "REVIEW_REPORT";
DROP TABLE "BOARD_REPORT";
DROP TABLE "BOARD_REPLY";
DROP TABLE "REVIEW_REPLY";
DROP TABLE "NOTICE_FILE";
DROP TABLE "FREEBOARD_FILE";
DROP TABLE "REVIEWBOARD_FILE";
DROP TABLE "ADM_IMG";
DROP TABLE "CLIENT_IMG";
DROP TABLE "ADMLOGIN_LOG";
DROP TABLE "LOGIN_LOG";
    DROP TABLE "FREEBOARD";
    DROP TABLE "REVIEWBOARD";
    DROP TABLE "NOTICEBOARD";
        DROP TABLE "CLIENT";
        DROP TABLE "ADMIN";
        DROP TABLE "MEMBER";
        
------- CREATE -------

CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_PWD"	VARCHAR2(20)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(100)		NOT NULL,
	"MEM_NICK"	VARCHAR2(24)		NOT NULL,
	"MEM_GRADE"	CHAR(1)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "MEMBER"."MEM_PWD" IS '비밀번호(영문, 숫자, 특수문자 포함 8~20자까지)';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '이메일(아이디 찾기 시 전달)';

COMMENT ON COLUMN "MEMBER"."MEM_NICK" IS '닉네임(한글 8자, 영어 24자까지 가능하게끔 설정)';

COMMENT ON COLUMN "MEMBER"."MEM_GRADE" IS '1: CLIENT, 0: ADMIN';



CREATE TABLE "CLIENT" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CLIENT_PWD"	VARCHAR2(20)		NOT NULL,
	"CLIENT_NICK"	VARCHAR2(24)		NOT NULL
);

COMMENT ON COLUMN "CLIENT"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "CLIENT"."CLIENT_PWD" IS '비밀번호(영문, 숫자, 특수문자 포함 8~20자까지)';

COMMENT ON COLUMN "CLIENT"."CLIENT_NICK" IS '닉네임(한글 8자, 영어 24자까지 가능하게끔 설정)';



CREATE TABLE "ADMIN" (
	"ADM_ID"	VARCHAR2(20)		NOT NULL,
	"ADM_DEPT"	VARCHAR2(100)		NOT NULL,
	"ADM_DATE"	VARCHAR2(24)		NOT NULL
);

COMMENT ON COLUMN "ADMIN"."ADM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "ADMIN"."ADM_DEPT" IS '이메일(아이디 찾기 시 전달)';

COMMENT ON COLUMN "ADMIN"."ADM_DATE" IS '닉네임(한글 8자, 영어 24자까지 가능하게끔 설정)';



CREATE TABLE "FREEBOARD" (
	"BOARD_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"BOARD_TITLE"	VARCHAR2(120)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"WRITE_TIME"	TIMESTAMP		NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"READ_GOOD"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "FREEBOARD"."BOARD_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "FREEBOARD"."BOARD_TITLE" IS '글제목 한글 40자, 영어 120자';

COMMENT ON COLUMN "FREEBOARD"."BOARD_CONTENT" IS '글내용 작성';

COMMENT ON COLUMN "FREEBOARD"."WRITE_TIME" IS '글작성 시간(YYYY-MI-SS HH:MM:SS)';

COMMENT ON COLUMN "FREEBOARD"."READ_COUNT" IS '글읽기시 1씩 증가';

COMMENT ON COLUMN "FREEBOARD"."READ_GOOD" IS '좋아요 버튼 누를 시 1씩 증가';

COMMENT ON COLUMN "FREEBOARD"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "REVIEWBOARD" (
	"REVIEW_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"REVIEW_TITLE"	VARCHAR2(120)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REVIEW_TIME"	TIMESTAMP		NOT NULL,
	"REVIEW_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"REVIEW_GOOD"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REVIEWBOARD"."REVIEW_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "REVIEWBOARD"."REVIEW_TITLE" IS '글제목 한글 40자, 영어 120자';

COMMENT ON COLUMN "REVIEWBOARD"."REVIEW_CONTENT" IS '글내용 작성';

COMMENT ON COLUMN "REVIEWBOARD"."REVIEW_TIME" IS '글작성 시간(YYYY-MI-SS HH:MM:SS)';

COMMENT ON COLUMN "REVIEWBOARD"."REVIEW_COUNT" IS '글읽기시 1씩 증가';

COMMENT ON COLUMN "REVIEWBOARD"."REVIEW_GOOD" IS '좋아요버튼 누른 횟수';

COMMENT ON COLUMN "REVIEWBOARD"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "NOTICEBOARD" (
	"NOTICE_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(120)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"NOTICE_TIME"	TIMESTAMP		NOT NULL,
	"ADM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NOTICEBOARD"."NOTICE_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "NOTICEBOARD"."NOTICE_TITLE" IS '글제목 한글 40자, 영어 120자';

COMMENT ON COLUMN "NOTICEBOARD"."NOTICE_CONTENT" IS '글내용 작성';

COMMENT ON COLUMN "NOTICEBOARD"."NOTICE_TIME" IS '글작성 시간(YYYY-MI-SS HH:MM:SS)';

COMMENT ON COLUMN "NOTICEBOARD"."ADM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "LOGIN_LOG" (
	"LOG_TIME"	TIMESTAMP		NOT NULL,
	"LOG_IP"	VARCHAR2(15)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"LOG_TYPE"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "LOGIN_LOG"."LOG_TIME" IS '로그인/아웃 시간';

COMMENT ON COLUMN "LOGIN_LOG"."LOG_IP" IS '로그인 단말기 IP4(000.000.000.000)';

COMMENT ON COLUMN "LOGIN_LOG"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "LOGIN_LOG"."LOG_TYPE" IS '로그인(1) 로그인(0)';



CREATE TABLE "NOTICE_FILE" (
	"BOARD_FILE_ID"	NUMBER(20)		NOT NULL,
	"NOTICE_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(300)		NOT NULL,
	"SAVED_FILE_PATH_NAME"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "NOTICE_FILE"."BOARD_FILE_ID" IS 'BOARD ID마다 1씩 증가';

COMMENT ON COLUMN "NOTICE_FILE"."NOTICE_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "NOTICE_FILE"."ORIGINAL_FILENAME" IS '클라이언트로 전송한 파일명';

COMMENT ON COLUMN "NOTICE_FILE"."SAVED_FILE_PATH_NAME" IS '파일경로(YYYYMMDDHHMMSS_00001.TXT';



CREATE TABLE "FREEBOARD_FILE" (
	"BOARD_FILE_ID"	NUMBER(20)		NOT NULL,
	"BOARD_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(300)		NOT NULL,
	"SAVED_FILE_PATH_NAME"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "FREEBOARD_FILE"."BOARD_FILE_ID" IS 'BOARD ID마다 1씩 증가';

COMMENT ON COLUMN "FREEBOARD_FILE"."BOARD_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "FREEBOARD_FILE"."ORIGINAL_FILENAME" IS '클라이언트로 전송한 파일명';

COMMENT ON COLUMN "FREEBOARD_FILE"."SAVED_FILE_PATH_NAME" IS '파일경로(YYYYMMDDHHMMSS_00001.TXT';



CREATE TABLE "REVIEWBOARD_FILE" (
	"BOARD_FILE_ID"	NUMBER(20)		NOT NULL,
	"REVIEW_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(300)		NOT NULL,
	"SAVED_FILE_PATH_NAME"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "REVIEWBOARD_FILE"."BOARD_FILE_ID" IS 'BOARD ID마다 1씩 증가';

COMMENT ON COLUMN "REVIEWBOARD_FILE"."REVIEW_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "REVIEWBOARD_FILE"."ORIGINAL_FILENAME" IS '클라이언트로 전송한 파일명';

COMMENT ON COLUMN "REVIEWBOARD_FILE"."SAVED_FILE_PATH_NAME" IS '파일경로(YYYYMMDDHHMMSS_00001.TXT';



CREATE TABLE "ADM_IMG" (
	"BOARD_FILE_ID"	NUMBER(20)		NOT NULL,
	"ADM_ID"	VARCHAR2(20)		NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(300)		NOT NULL,
	"SAVED_FILE_PATH_NAME"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "ADM_IMG"."BOARD_FILE_ID" IS 'BOARD ID마다 1씩 증가';

COMMENT ON COLUMN "ADM_IMG"."ADM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "ADM_IMG"."ORIGINAL_FILENAME" IS '클라이언트로 전송한 파일명';

COMMENT ON COLUMN "ADM_IMG"."SAVED_FILE_PATH_NAME" IS '파일경로(YYYYMMDDHHMMSS_00001.TXT';



CREATE TABLE "CLIENT_IMG" (
	"BOARD_FILE_ID"	NUMBER(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(300)		NOT NULL,
	"SAVED_FILE_PATH_NAME"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "CLIENT_IMG"."BOARD_FILE_ID" IS 'BOARD ID마다 1씩 증가';

COMMENT ON COLUMN "CLIENT_IMG"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "CLIENT_IMG"."ORIGINAL_FILENAME" IS '클라이언트로 전송한 파일명';

COMMENT ON COLUMN "CLIENT_IMG"."SAVED_FILE_PATH_NAME" IS '파일경로(YYYYMMDDHHMMSS_00001.TXT';



CREATE TABLE "ADMLOGIN_LOG" (
	"LOG_TIME"	TIMESTAMP		NOT NULL,
	"LOG_IP"	VARCHAR2(15)		NOT NULL,
	"ADM_ID"	VARCHAR2(20)		NOT NULL,
	"LOG_TYPE"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "ADMLOGIN_LOG"."LOG_TIME" IS '로그인/아웃 시간';

COMMENT ON COLUMN "ADMLOGIN_LOG"."LOG_IP" IS '로그인 단말기 IP4(000.000.000.000)';

COMMENT ON COLUMN "ADMLOGIN_LOG"."ADM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "ADMLOGIN_LOG"."LOG_TYPE" IS '로그인(1) 로그인(0)';



CREATE TABLE "BOARD_REPLY" (
	"BOARD_REPLY_ID"	NUMBER		NOT NULL,
	"BOARD_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"BOARD_REPLY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_REPLY_LOG_IP"	VARCHAR2(15)		NULL,
	"BOARD_REPLY_LEVEL"	NUMBER(2)	DEFAULT 1	NOT NULL,
	"BOARD_REPLY_REF"	NUMBER		NOT NULL,
	"BOARD_REPLY_STEP"	NUMBER(3)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_ID" IS '댓글 - 1단계';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_LOG_IP" IS '글작성한 단말의 IP4 (000.000.000.000)';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_LEVEL" IS '댓글1, 대댓글2, 대대댓글3';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_REF" IS '최초 댓글(BOARD_REPLY_LEVEL:1)의 번호 BOARD_REPLY_ID';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_REPLY_STEP" IS '최초 댓글기준으로 몇번째 위치인지 나타냄';

COMMENT ON COLUMN "BOARD_REPLY"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "REVIEW_REPLY" (
	"BOARD_REPLY_ID"	NUMBER		NOT NULL,
	"REVIEW_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"BOARD_REPLY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_REPLY_WRITE_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BOARD_REPLY_LOG_IP"	VARCHAR2(15)		NULL,
	"BOARD_REPLY_LEVEL"	NUMBER(2)	DEFAULT 1	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REVIEW_REPLY"."BOARD_REPLY_ID" IS '댓글 - 1단계';

COMMENT ON COLUMN "REVIEW_REPLY"."REVIEW_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "REVIEW_REPLY"."BOARD_REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "REVIEW_REPLY"."BOARD_REPLY_WRITE_TIME" IS '작성시간';

COMMENT ON COLUMN "REVIEW_REPLY"."BOARD_REPLY_LOG_IP" IS '글작성한 단말의 IP4 (000.000.000.000)';

COMMENT ON COLUMN "REVIEW_REPLY"."BOARD_REPLY_LEVEL" IS '댓글1, 대댓글2, 대대댓글3';

COMMENT ON COLUMN "REVIEW_REPLY"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "BOARD_REPORT" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_ID"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD_REPORT"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_ID" IS '게시글 마다 임의의 숫자 부여';



CREATE TABLE "REVIEW_REPORT" (
	"REVIEW_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REVIEW_REPORT"."REVIEW_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "REVIEW_REPORT"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "REPLY1_REPORT" (
	"BOARD_REPLY_ID"	NUMBER		NOT NULL,
	"REVIEW_ID"	NUMBER	DEFAULT 1	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REPLY1_REPORT"."BOARD_REPLY_ID" IS '댓글 - 1단계';

COMMENT ON COLUMN "REPLY1_REPORT"."REVIEW_ID" IS '게시글 마다 임의의 숫자 부여';

COMMENT ON COLUMN "REPLY1_REPORT"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';



CREATE TABLE "REPLY2_REPORT" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_REPLY_ID"	NUMBER		NOT NULL,
	"BOARD_ID"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "REPLY2_REPORT"."MEM_ID" IS '아이디(영문,숫자 포함 20자까지)';

COMMENT ON COLUMN "REPLY2_REPORT"."BOARD_REPLY_ID" IS '댓글 - 1단계';

COMMENT ON COLUMN "REPLY2_REPORT"."BOARD_ID" IS '게시글 마다 임의의 숫자 부여';



------- CONSTRAINT -------

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADM_ID"
);

ALTER TABLE "LOGIN_LOG" ADD CONSTRAINT "PK_LOGIN_LOG" PRIMARY KEY (
	"LOG_TIME",
	"LOG_IP",
	"MEM_ID"
);

ALTER TABLE "FREEBOARD" ADD CONSTRAINT "PK_FREEBOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "REVIEWBOARD" ADD CONSTRAINT "PK_REVIEWBOARD" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "NOTICEBOARD" ADD CONSTRAINT "PK_NOTICEBOARD" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "REVIEW_REPORT" ADD CONSTRAINT "PK_REVIEW_REPORT" PRIMARY KEY (
	"REVIEW_ID",
	"MEM_ID"
);

ALTER TABLE "NOTICE_FILE" ADD CONSTRAINT "PK_NOTICE_FILE" PRIMARY KEY (
	"BOARD_FILE_ID",
	"NOTICE_ID"
);

ALTER TABLE "FREEBOARD_FILE" ADD CONSTRAINT "PK_FREEBOARD_FILE" PRIMARY KEY (
	"BOARD_FILE_ID",
	"BOARD_ID"
);

ALTER TABLE "REVIEWBOARD_FILE" ADD CONSTRAINT "PK_REVIEWBOARD_FILE" PRIMARY KEY (
	"BOARD_FILE_ID",
	"REVIEW_ID"
);

ALTER TABLE "ADM_IMG" ADD CONSTRAINT "PK_ADM_IMG" PRIMARY KEY (
	"BOARD_FILE_ID",
	"ADM_ID"
);

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "PK_REVIEW_REPLY" PRIMARY KEY (
	"BOARD_REPLY_ID",
	"REVIEW_ID"
);

ALTER TABLE "REPLY1_REPORT" ADD CONSTRAINT "PK_REPLY1_REPORT" PRIMARY KEY (
	"BOARD_REPLY_ID",
	"REVIEW_ID",
	"MEM_ID"
);

ALTER TABLE "CLIENT_IMG" ADD CONSTRAINT "PK_CLIENT_IMG" PRIMARY KEY (
	"BOARD_FILE_ID",
	"MEM_ID"
);

ALTER TABLE "ADMLOGIN_LOG" ADD CONSTRAINT "PK_ADMLOGIN_LOG" PRIMARY KEY (
	"LOG_TIME",
	"LOG_IP",
	"ADM_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "PK_BOARD_REPLY" PRIMARY KEY (
	"BOARD_REPLY_ID",
	"BOARD_ID"
);

ALTER TABLE "REPLY2_REPORT" ADD CONSTRAINT "PK_REPLY2_REPORT" PRIMARY KEY (
	"MEM_ID",
	"BOARD_REPLY_ID",
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "PK_BOARD_REPORT" PRIMARY KEY (
	"MEM_ID",
	"BOARD_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_MEMBER_TO_ADMIN_1" FOREIGN KEY (
	"ADM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "LOGIN_LOG" ADD CONSTRAINT "FK_CLIENT_TO_LOGIN_LOG_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "CLIENT" (
	"MEM_ID"
);

ALTER TABLE "FREEBOARD" ADD CONSTRAINT "FK_MEMBER_TO_FREEBOARD_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "REVIEWBOARD" ADD CONSTRAINT "FK_MEMBER_TO_REVIEWBOARD_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "NOTICEBOARD" ADD CONSTRAINT "FK_ADMIN_TO_NOTICEBOARD_1" FOREIGN KEY (
	"ADM_ID"
)
REFERENCES "ADMIN" (
	"ADM_ID"
);

ALTER TABLE "REVIEW_REPORT" ADD CONSTRAINT "FK_REVIEWBOARD_TO_REVIEW_REPORT_1" FOREIGN KEY (
	"REVIEW_ID"
)
REFERENCES "REVIEWBOARD" (
	"REVIEW_ID"
);

ALTER TABLE "REVIEW_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "NOTICE_FILE" ADD CONSTRAINT "FK_NOTICEBOARD_TO_NOTICE_FILE_1" FOREIGN KEY (
	"NOTICE_ID"
)
REFERENCES "NOTICEBOARD" (
	"NOTICE_ID"
);

ALTER TABLE "FREEBOARD_FILE" ADD CONSTRAINT "FK_FREEBOARD_TO_FREEBOARD_FILE_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "FREEBOARD" (
	"BOARD_ID"
);

ALTER TABLE "REVIEWBOARD_FILE" ADD CONSTRAINT "FK_REVIEWBOARD_TO_REVIEWBOARD_FILE_1" FOREIGN KEY (
	"REVIEW_ID"
)
REFERENCES "REVIEWBOARD" (
	"REVIEW_ID"
);

ALTER TABLE "ADM_IMG" ADD CONSTRAINT "FK_ADMIN_TO_ADM_IMG_1" FOREIGN KEY (
	"ADM_ID"
)
REFERENCES "ADMIN" (
	"ADM_ID"
);

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "FK_REVIEWBOARD_TO_REVIEW_REPLY_1" FOREIGN KEY (
	"REVIEW_ID"
)
REFERENCES "REVIEWBOARD" (
	"REVIEW_ID"
);

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_REPLY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "CLIENT_IMG" ADD CONSTRAINT "FK_CLIENT_TO_CLIENT_IMG_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "CLIENT" (
	"MEM_ID"
);

ALTER TABLE "ADMLOGIN_LOG" ADD CONSTRAINT "FK_ADMIN_TO_ADMLOGIN_LOG_1" FOREIGN KEY (
	"ADM_ID"
)
REFERENCES "ADMIN" (
	"ADM_ID"
);

ALTER TABLE "CLIENT" ADD CONSTRAINT "FK_MEMBER_TO_CLIENT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "FK_FREEBOARD_TO_BOARD_REPLY_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "FREEBOARD" (
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPLY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_FREEBOARD_TO_BOARD_REPORT_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "FREEBOARD" (
	"BOARD_ID"
);

ALTER TABLE "REPLY1_REPORT" ADD CONSTRAINT "FK_REVIEW_REPLY_TO_REPLY1_REPORT_1" FOREIGN KEY (
	"BOARD_REPLY_ID" , "REVIEW_ID"
)
REFERENCES "REVIEW_REPLY" (
	"BOARD_REPLY_ID" , "REVIEW_ID"
);

ALTER TABLE "REPLY1_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPLY1_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "REPLY2_REPORT" ADD CONSTRAINT "FK_BOARD_REPLY_TO_REPLY2_REPORT_1" FOREIGN KEY (
	"BOARD_REPLY_ID", "BOARD_ID"
)
REFERENCES "BOARD_REPLY" (
	"BOARD_REPLY_ID", "BOARD_ID"
);


ALTER TABLE "REPLY2_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPLY2_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);